# Generated by Django 3.1.5 on 2021-01-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('decision_maker', models.CharField(blank=True, max_length=255, verbose_name='ЛПР')),
                ('phone', models.PositiveIntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('first_call', models.TextField(blank=True, verbose_name='Первый звонок')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Комментарий')),
                ('next_call', models.TextField(blank=True, verbose_name='Следующий звонок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ссылка на клиента')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('responsible', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('title',),
            },
        ),
    ]
